# Generated by Django 2.2.1 on 2019-07-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('stu_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('class_num', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('qq_num', models.CharField(max_length=30)),
            ],
        ),
    ]
