# Generated by Django 2.2.1 on 2019-07-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPerson',
            fields=[
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('stu_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('class_num', models.CharField(max_length=10, verbose_name='班级')),
                ('school', models.CharField(max_length=10, verbose_name='校区')),
                ('department', models.CharField(max_length=10, verbose_name='意向部门')),
                ('phone', models.CharField(max_length=15, verbose_name='手机号')),
                ('qq_num', models.CharField(max_length=15, verbose_name='QQ号')),
                ('changeable', models.CharField(max_length=2, verbose_name='是否接受调剂')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
