# Generated by Django 2.2.1 on 2019-07-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20190712_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeXiePerson',
            fields=[
                ('kexie_id', models.CharField(max_length=10, verbose_name='编号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('stu_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学号')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('school', models.CharField(max_length=10, verbose_name='校区')),
                ('department', models.CharField(max_length=10, verbose_name='部门')),
                ('department_job', models.CharField(max_length=10, verbose_name='部门职务')),
                ('class_num', models.CharField(max_length=10, verbose_name='班级')),
                ('academy', models.CharField(max_length=20, verbose_name='学院')),
                ('qq_num', models.CharField(max_length=15, verbose_name='QQ号')),
                ('phone', models.CharField(max_length=15, verbose_name='手机号')),
                ('dorm', models.CharField(max_length=15, verbose_name='宿舍')),
                ('year', models.CharField(max_length=15, verbose_name='入学年份')),
            ],
            options={
                'verbose_name': '科仔信息',
                'verbose_name_plural': '科仔信息',
            },
        ),
        migrations.AlterModelOptions(
            name='newperson',
            options={'verbose_name': '小萌新', 'verbose_name_plural': '小萌新名单'},
        ),
    ]
