# Generated by Django 2.2.4 on 2019-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_auto_20190713_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newperson',
            name='stu_id',
        ),
        migrations.AlterField(
            model_name='newperson',
            name='phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='手机号'),
        ),
    ]
